server.port=8080
spring.application.name=java-backend

app.data-file=data/data.json

auth.enabled=false
auth.header-name=X-API-Key
auth.api-keys=demo-key-123,client-key-456

ratelimit.enabled=true
ratelimit.requests-per-minute=120

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{0} - %msg%n
logging.level.com.developer.test=INFO
logging.level.access=INFO
